#
# 支持服务：
#
version: '2'
services:
  oauth-client:
    image: xxxx
    container_name: oauth-client
    hostname: oauth-client
    ports:
      - '0.0.0.0:8000:80'
    networks:
      net:
        ipv4_address: 172.30.0.12

# 创建桥接网络
networks:
  # 桥接网络名称，配合文件前缀，最后为dev_test_env_net  参考：https://www.jianshu.com/p/d70c61d45364
  net:
    driver: bridge
    # external: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          # 网关
          gateway: 172.30.0.1
