/**
 * 包级常量（skill 名、路径约定）。
 * 包名 / 版本一律从 package.json 读取，见 paths.ts。
 */

/** 本包装载并允许同步的 skill 目录名；永不含 business-map 等仓库私有 skill */
export const CORE_SKILL_NAMES = [
  'workflow',
  'code-dev',
  'self-check',
  'commit',
] as const

export type CoreSkillName = (typeof CORE_SKILL_NAMES)[number]

/** 下游项目中，仅本仓业务 skill 目录名（永不覆盖） */
export const BUSINESS_MAP_SKILL_NAME = 'business-map'

/** 下游 skills 相对根目录片段 */
export const DOWNSTREAM_SKILLS_SEGMENTS = ['.agents', 'skills'] as const

/**
 * 同步基线文件名（隐含文件：点开头 + 业务命名 `agent-skills`）。
 *
 * 用途：记录「本次从包内 skills/ 同步到下游 .agents/skills/ 的基线」，
 *       供 `agent-skills:check` 比对漂移（包名/版本/时间/synced skills 列表）。
 * 命名约定：
 *   - `agent-skills` 明确这是 agent-skills 工具的产物，而非其它系统生成
 *   - 单一基线文件，涵盖原 `.agent-skills-baseline.json` + `.sync-manifest.json` 的全部信息
 * 每次 `apply` 成功后覆写；上游包版本变更或 skill 列表变更后必须重新 apply。
 *
 * ⚠️ 历史：
 *   - v0.0.1-alpha.0 早期版本同时生成 `.agent-skills-baseline.json` 与 `.sync-manifest.json` 两份
 *   - 现合并为单一 `agent-skills.json`，避免双文件语义重复 / 漂移
 */
export const AGENT_SKILLS_BASELINE_FILE_NAME = 'agent-skills.json'

/** CLI 环境变量：未传 --target 时可用 */
export const ENV_AGENT_SKILLS_TARGET = 'AGENT_SKILLS_TARGET'

/** 基线备注 */
export const AGENT_SKILLS_BASELINE_NOTE
  = 'Source of truth is the published package skills/. Generated by vip-agent-skills. business-map is repo-local and never synced.'
