name: CI

# 触发条件
on:
  pull_request:
    branches:
      - next
    push:
      branches:
        - next

  # 手动触发部署
  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

jobs:
  # 本地构建
  Base-Build:
    name: 基础编译构建
    runs-on: ubuntu-latest
    if: github.repository == '142vip/core-x' &&  github.event_name == 'pull_request'
    permissions:
      actions: read
      pull-requests: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      # 安装PNPM
      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
